### ISSUE TITLE
Use of BdvHandle instead of BdvHandlePanel when adding to an existing bdv ?

### ISSUE THREAD

**Issue by NicoKiaru** [juglab/LabelEditor#16]
Hello, 

In this line:

https://github.com/juglab/LabelEditor/blob/7b3e020a6be994444d6427ac5baa4bdb5c9b0332/src/test/java/sc/fiji/labeleditor/howto/advanced/E01_AddToExistingBDV.java#L47

an object of class `BdvHandlePanel` is expected. Would it be possible to make this function less strict and use `BdvHandle` ? Or maybe make it accept a `BdvHandleWindow` ?

Thanks!

**Comment by frauzufall** [comment]
That was a good idea, I changed it to `BdvHandle`, it's released with `0.6.0` :)
